name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - name: Build Electron App
        run: pnpm run build:win
        env:
          GITHUB_TOKEN: "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"